const data = {
  products: [
    {
      name: "Espresso",
      category: "HOT CLASSICS",
      image: "/images/espresso.jpeg",
      price: 70,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "Great espresso drink",
    },
    {
      name: "Affogato",
      category: "HOT CLASSICS",
      image: "/images/AFFOGATO.jpeg",
      price: 80,
      brand: "Adidas",
      rating: 4.2,
      numReviews: 10,
      countInStock: 20,
      description: "A popular shirt",
    },
    {
      name: "HOT CLASSICS",
      category: "CAPPUCCINO",
      image: "/images/cappacino.jpeg",
      price: 90,
      brand: "Raymond",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "A popular shirt",
    },
    {
      name: "CAFÉ LATTE",
      category: "HOT CLASSICS",
      image: "/images/cafe-latte.jpeg",
      price: 90,
      brand: "Oliver",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "Smart looking pants",
    },
    {
      name: "BARRISTA",
      category: "COLD CLASSICS",
      image: "/images/barista.jpeg",
      price: 95,
      brand: "Zara",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "A popular pants",
    },
    {
      name: "ICED AMERICANO",
      category: "COLD CLASSICS",
      image: "/images/iced-americano.jpeg",
      price: 75,
      brand: "Casely",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "A popular pants",
    },
    {
      name: "SMOOTHIES",
      category: "COLD CLASSICS",
      image: "/images/smoothie.png",
      price: 75,
      brand: "Casely",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "A popular pants",
    },
    {
      name: "GINGER HONEY",
      category: "TEA",
      image: "/images/ginger-honey.png",
      price: 75,
      brand: "Casely",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "A popular pants",
    },
    {
      name: "GREEN TEA",
      category: "TEA",
      image: "/images/green-tea.jpeg",
      price: 75,
      brand: "Casely",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "A popular pants",
    },
    {
      name: "ASSAM TEA",
      category: "TEA",
      image: "/images/assam-tea.jpeg",
      price: 75,
      brand: "Casely",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "A popular pants",
    },
    {
      name: "JAMUN BANTA",
      category: "MOJITOS / LEMONADES",
      image: "/images/jamun-banta.jpeg",
      price: 75,
      brand: "Casely",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "A popular pants",
    },
    {
      name: "FIZZY LEMONGRASS",
      category: "MOJITOS / LEMONADES",
      image: "/images/ginger-lemongrass.jpeg",
      price: 75,
      brand: "Casely",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "A popular pants",
    },
    {
      name: "GREEN APPLE LEMONADE",
      category: "MOJITOS / LEMONADES",
      image: "/images/green-apple-lemonade.png",
      price: 75,
      brand: "Casely",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "A popular pants",
    },
    {
      name: "CLASSIC MOJITO",
      category: "MOJITOS / LEMONADES",
      image: "/images/classic-mojito.jpeg",
      price: 75,
      brand: "Casely",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "A popular pants",
    },
    {
      name: "PEACH ICED TEA",
      category: "ICED TEAS",
      image: "/images/peach-ice-tea.png",
      price: 75,
      brand: "Casely",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "A popular pants",
    },
    {
      name: "LEMON ICED TEA",
      category: "ICED TEAS",
      image: "/images/lemon-ice-tea.jpeg",
      price: 75,
      brand: "Casely",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "A popular pants",
    },
  ],
};
export default data;
