const data = {
  products: [
    {
      name: "Espresso",
      category: "HOT CLASSICS",
      image: "/images/espresso.jpeg",
      price: 70,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "Great espresso drink",
    },
    {
      name: "Affogato",
      category: "HOT CLASSICS",
      image: "/images/AFFOGATO.jpeg",
      price: 80,
      brand: "Adidas",
      rating: 4.2,
      numReviews: 10,
      countInStock: 20,
      description: "A popular shirt",
    },
    {
      name: "Hot Classics",
      category: "CAPPUCCINO",
      image: "/images/cappacino.jpeg",
      price: 90,
      brand: "Raymond",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "A popular shirt",
    },
    {
      name: "Café Latte",
      category: "HOT CLASSICS",
      image: "/images/cafe-latte.jpeg",
      price: 90,
      brand: "Oliver",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "Smart looking pants",
    },
    {
      name: "Barista",
      category: "COLD CLASSICS",
      image: "/images/barista.jpeg",
      price: 95,
      brand: "Zara",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "A popular pants",
    },
    {
      name: "Iced Americano",
      category: "COLD CLASSICS",
      image: "/images/iced-americano.jpeg",
      price: 75,
      brand: "Casely",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "A popular pants",
    },
    {
      name: "Smoothies",
      category: "COLD CLASSICS",
      image: "/images/smoothie.png",
      price: 75,
      brand: "Casely",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "A popular pants",
    },
    {
      name: "Ginger Honey",
      category: "TEA",
      image: "/images/ginger-honey.png",
      price: 75,
      brand: "Casely",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "A popular pants",
    },
    {
      name: "Green Tea",
      category: "TEA",
      image: "/images/green-tea.jpeg",
      price: 75,
      brand: "Casely",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "A popular pants",
    },
    {
      name: "Assam Tea",
      category: "TEA",
      image: "/images/assam-tea.jpeg",
      price: 75,
      brand: "Casely",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "A popular pants",
    },
    {
      name: "Jamun Banta",
      category: "MOJITOS / LEMONADES",
      image: "/images/jamun-banta.jpeg",
      price: 75,
      brand: "Casely",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "A popular pants",
    },
    {
      name: "Fizzy Lemon Grass",
      category: "MOJITOS / LEMONADES",
      image: "/images/ginger-lemongrass.jpeg",
      price: 75,
      brand: "Casely",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "A popular pants",
    },
    {
      name: "Green Apple Lemonade",
      category: "MOJITOS / LEMONADES",
      image: "/images/green-apple-lemonade.png",
      price: 75,
      brand: "Casely",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "A popular pants",
    },
    {
      name: "Classic Mojito",
      category: "MOJITOS / LEMONADES",
      image: "/images/classic-mojito.jpeg",
      price: 75,
      brand: "Casely",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "A popular pants",
    },
    {
      name: "Peach Iced Tea",
      category: "ICED TEAS",
      image: "/images/peach-ice-tea.png",
      price: 75,
      brand: "Casely",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "A popular pants",
    },
    {
      name: "Lemon Iced Tea",
      category: "ICED TEAS",
      image: "/images/lemon-ice-tea.jpeg",
      price: 75,
      brand: "Casely",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "A popular pants",
    },
  ],
};
export default data;
